### ISSUE TITLE
About the BinaryQuantization bugs

### ISSUE THREAD

**Issue by Siyuluan** [UCMerced-ML/LC-model-compression#2]
Hi,

Thank you for your great work, I learned a lot.

I wonder if you can give some toy examples about BinaryQuantization, ScaledBinaryQuantization,ScaledTernaryQuantization?

Because when I used the BinaryQuantization, it shows :

compression_tasks[Param(w, device)] = (AsVector, BinaryQuantization(), f'task_{i}')
TypeError: Can't instantiate abstract class BinaryQuantization with abstract methods load_state_dict, uncompress_state

Thank you so much.

**Comment by akamaster** [comment]
HI Siyuluan, 
Thanks for reporting these bugs, I'll look into it shortly.

**Comment by akamaster** [comment]
Hi again, 
The issue was fixed in https://github.com/UCMerced-ML/LC-model-compression/commit/117b25a21f16303016ab779774025d5830578da9

We have added several examples, including one in google colab: [click here to open in colab](https://colab.research.google.com/github/UCMerced-ML/LC-model-compression/blob/master/examples/lenet300/lenet300_collab_lc_example.ipynb)

**Comment by Siyuluan** [comment]
> 
Hi,

Thank you for your reply! :D 

Have a nice day.
